services:
  db:
    image: postgres:17.2-bookworm
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: ./postgres.env
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/portfolio/app
    env_file:
      - ./postgres.env
    depends_on:
      - db

volumes:
  postgres: