# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.3.6
FROM ruby:$RUBY_VERSION-bookworm AS base

# Rails app lives here
WORKDIR /usr/portfolio/app

ENV RAILS_ENV="development"

# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    curl \
    libjemalloc2 \
    libvips \
    postgresql-client \
    build-essential \
    git \
    libpq-dev \
    nodejs \
    npm \
    pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install application gems
COPY Gemfile* ./
RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    bundle exec bootsnap precompile --gemfile

# Install javascript packages
RUN npm install -g yarn 

COPY package*.json ./
RUN yarn install

ARG DEFAULT_PORT 3000

EXPOSE ${DEFAULT_PORT}

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
