x-app: &app
  build:
    context: .
    dockerfile: ./Dockerfile.dev
  volumes:
    - .:/usr/portfolio/app
  env_file:
    - ./postgres.env
  depends_on:
    - db

services:
  app:
    <<: *app
    environment:
      SHAKAPACKER_DEV_SERVER_HOST: shakapacker
      SHAKAPACKER_DEV_SERVER_PORT: 3035
    command: /bin/sh

  shakapacker:
    <<: *app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        DEFAULT_PORT: 3035
    environment:
      SHAKAPACKER_DEV_SERVER_HOST: 0.0.0.0
      SHAKAPACKER_DEV_SERVER_PORT: 3035
    command: ./bin/shakapacker-dev-server
    ports:
      - 3035:3035

  web:
    <<: *app
    ports:
      - 3000:3000
    depends_on:
      - app
      - redis

  sidekiq:
    <<: *app
    command: bundle exec sidekiq
    depends_on:
      - redis

  db:
    image: postgres:17.2-bookworm
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: ./postgres.env

  redis:
    image: redis:7.4.2-bookworm
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  postgres:
  node-modules:
  redis-data:
